import 'package:flutter/material.dart';
import 'package:spendysync/models/expense_model.dart';
import 'package:spendysync/services/expense_service.dart';
import 'package:spendysync/models/user_model.dart';

class AddExpense extends StatefulWidget {
  final UserModel user;
  const AddExpense({super.key, required this.user});

  @override
  _AddExpenseState createState() => _AddExpenseState();
}

class _AddExpenseState extends State<AddExpense> {
  final ExpenseService _expenseService = ExpenseService();
  final _formKey = GlobalKey<FormState>();
  String category = "";
  double amount = 0.0;

  void _submitExpense() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      Expense newExpense = Expense(
        id: "", // Will be auto-generated by Supabase
        userId: widget.user.userId,
        category: category,
        amount: amount,
        date: DateTime.now(),
      );

      await _expenseService.addExpense(newExpense);
      Navigator.pop(context); // Close form after saving
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Add Expense")),
      body: Padding(
        padding: EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: InputDecoration(labelText: "Category"),
                onSaved: (value) => category = value!,
                validator: (value) =>
                    value!.isEmpty ? "Please enter a category" : null,
              ),
              TextFormField(
                decoration: InputDecoration(labelText: "Amount"),
                keyboardType: TextInputType.number,
                onSaved: (value) => amount = double.parse(value!),
                validator: (value) =>
                    value!.isEmpty ? "Please enter an amount" : null,
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitExpense,
                child: Text("Save Expense"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
